server:
  port: 8761
spring:
  application:
    name: lanjing-eureka
  security:
    user:
      name: lanjing
      password: 123456

# eureka
eureka:
  # begin  配置关闭自我保护，并配置Eureka Server清理无效节点的时间间隔
  server:
    enable-self-preservation: false         # 设为false，关闭自我保护
    eviction-interval-timer-in-ms: 30000    # 清理间隔（单位毫秒，默认是60*1000）
  # end
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false     # 当前服务不需要到Eureka Server上注册
    fetchRegistry: false          # 不需要从eureka服务器获取注册信息
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/   # Eureka客户端设置Eureka Server的地址
